### ISSUE TITLE
File browser: Download not working, mysql error

### ISSUE THREAD

**Issue by inbe** [Bonfire-Modules/file_manager#38]
(via download button in filebrowser)

**Comment by Janne-** [comment]
Solved: https://github.com/Bonfire-Modules/file_manager/commit/2e31156f4d8fd94f51937d0fbe5820c6726ee9ab

**Comment by inbe** [comment]
Fixed: 2b0cc38d0828d62dfdcb2eb1989125d5c4b0c12f
